webtalk_init -webtalk_dir C:/Users/macas/Documents/Xilinx/113_MP1/113_MP1.sim/sim_1/synth/timing/xsim/xsim.dir/tb_processor_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 17 05:12:37 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c45f0623-d0fa-4bd0-9025-0270f131627f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "099346e7572c4561acc445bc6a0930d7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "420 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "88604_KB" -context "xsim\\usage"
webtalk_transmit -clientid 316415442 -regid "" -xml C:/Users/macas/Documents/Xilinx/113_MP1/113_MP1.sim/sim_1/synth/timing/xsim/xsim.dir/tb_processor_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/macas/Documents/Xilinx/113_MP1/113_MP1.sim/sim_1/synth/timing/xsim/xsim.dir/tb_processor_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/macas/Documents/Xilinx/113_MP1/113_MP1.sim/sim_1/synth/timing/xsim/xsim.dir/tb_processor_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
